Solution
itmo-java-basics-2020/task-3-hashtable-classes-inner-classes-class-object-Idutvuker pull request #1
Opened 2020-03-13 04:16 UTC by Idutvuker

2020-03-23 18:29 UTC, ruperson commented
бранч dev

2020-03-23 18:29 UTC, ruperson commented
в след раз пожалста

2020-03-23 21:15 UTC, ruperson commented
оу 
у тебя табы а не пробелы........................................................

2020-03-23 21:17 UTC, ruperson requested changes
в остальном норм

2020-03-23 21:17 UTC, ruperson commented on src/main/java/ru/itmo/java/HashTable.java
> +	private class Pair {
вложенный класс в самый низ

2020-03-23 21:17 UTC, ruperson commented on src/main/java/ru/itmo/java/HashTable.java
> +	Object put(Object key, Object value) {
паблик

2020-03-23 21:17 UTC, ruperson commented on src/main/java/ru/itmo/java/HashTable.java
> +	private void resize() {
приватные методы после публичных

2020-03-23 21:17 UTC, ruperson commented on src/main/java/ru/itmo/java/HashTable.java
> +		if (table[hc] == null) {
ты в ветках делаешь ретурн
елсе не нужен

2020-03-23 21:17 UTC, ruperson commented on src/main/java/ru/itmo/java/HashTable.java
> +	private int capacity;
капасити сайз риалсайз тресхолд
неужели все используется?

2020-03-29 13:40 UTC, Idutvuker commented on src/main/java/ru/itmo/java/HashTable.java
> +	private int capacity;
Да.

2020-03-29 13:40 UTC, Idutvuker commented on src/main/java/ru/itmo/java/HashTable.java
> +	Object put(Object key, Object value) {
В исходном репозитории паблик не стоит.

2020-03-29 13:40 UTC, Idutvuker commented on src/main/java/ru/itmo/java/HashTable.java
> +		if (table[hc] == null) {
Я понимаю, что он не обязателен, но считаю, что так легче читается код.

2020-03-29 13:40 UTC, Idutvuker commented on src/main/java/ru/itmo/java/HashTable.java
> +	private void resize() {
В документации oracle написано, что так делать и надо: "These methods should be grouped by functionality rather than by scope or accessibility. For example, a private class method can be in between two public instance methods. The goal is to make reading and understanding the code easier."

https://www.oracle.com/technetwork/java/codeconventions-141855.html

2020-03-29 13:40 UTC, Idutvuker commented on src/main/java/ru/itmo/java/HashTable.java
> +	private class Pair {
158593fed9b9222675b6f79365f96b3dd463f978

2020-03-29 13:41 UTC, merged

2020-06-07 15:21 UTC, ruperson commented on src/main/java/ru/itmo/java/HashTable.java
> +	Object put(Object key, Object value) {
ловушка джокера

2020-06-07 15:25 UTC, ruperson commented on src/main/java/ru/itmo/java/HashTable.java
> +		if (table[hc] == null) {
ну не